package com.example.yininghuang.weather.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "city".
 */
public class City {

    private String id;
    private String cityName;
    private String province;

    public City() {
    }

    public City(String id) {
        this.id = id;
    }

    public City(String id, String cityName, String province) {
        this.id = id;
        this.cityName = cityName;
        this.province = province;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

}
